# -*- coding: utf-8 -*-
"""
Reading a mcc-file generated by "Beam Adjust" using "Octavius 1600 XDR"
Create an interpolated mcc-file 

J. Horn
"""

import re
import numpy as np

# Open file, read data       
def read_mcc_data(file):
    # Define variables 
    dose_values = []
    chamber_number = []
  
    # Load chamber layout OD1600XDR 
    detector_layout = np.load('layout_OD1600XDR.npy')
    
    # Extract only dose values and chamber indices
    string_pattern = re.compile('#') 
    with open(file) as raw_data:
        for line in raw_data:
            if string_pattern.search(line):
                values = line.split('\t')
                dose_values.append(float(values[5]))
                chamber_value = values[7].strip('#\n')
                chamber_number.append(int(chamber_value))
        dose_values = np.array(dose_values)
        chamber_number = np.array(chamber_number)
        
        # cut last three blocks = central profile, first and second diagonal
        dose_values = dose_values[0:-135]
        chamber_number = chamber_number[0:-135]
        mcc_data_container = np.array([chamber_number,dose_values])
        
    # Copy of layout, store dose values, keep nan
    dose_matrix = detector_layout.copy()
    for col in range(dose_matrix.shape[0]):
        for row in range(dose_matrix.shape[1]):
            if not np.isnan(dose_matrix[row, col]):
                # Find the index in mccDataContainer where the chamber number matches doseMatrix[row, col]
                buffer = np.where(mcc_data_container[0] == dose_matrix[row, col])
                if buffer[0].size > 0:  # Check if there is at least one match
                    # Extract the first match index
                    buffer = buffer[0][0]
                    # Get the corresponding dose value
                    dose = mcc_data_container[1][buffer]
                    # Assign the dose value to doseMatrix
                    dose_matrix[row, col] = dose
                
                
    dose_array = dose_matrix
    
    return dose_array

# Example usage
file_path = "N:\Desktop\original.mcc"
doseArray = read_mcc_data(file_path)
